### ISSUE TITLE
Cancel reservation operation

### ISSUE THREAD

**Issue by shanys8** [platformq/hotel_beds#4]
Hi Ryan

My name is Shany and I am a software developer at Roomer.  https://www.roomertravel.com/
We are integration with Hotelbeds so I'm using your API which was really helpful!
I have a question though regarding the cancellation process -
I can see that the gem is missing the implementation of the purchaseCancelRQ (as it is written in hotelbeds API), while PurchaseFlushRQ and ServiceRemoveRQ exists.
I asked the support team regarding the cancellation process and the answer is you must use the purchaseCancelRQ method in order to cancel reservation.
Do you know of a way to do that using the gem with the existing requests implemented?
Appreciate your help,
Shany

**Comment by netloner** [comment]
Hi Shany, you can check my fork, cancellation is done just days ago:)

**Comment by shanys8** [comment]
Really?? that's good news! couldn't manage to find it in your git thought, could you please send me the link to the repo?

**Comment by netloner** [comment]
Here is my fork:  https://github.com/netloner/hotel_beds

Hope this will be helpful : )

**Comment by shanys8** [comment]
Awesome! Exactly what I was looking for! :)

**Comment by ryantownsend** [comment]
If you'd like it merging in @netloner, please send me a pull request.

**Comment by netloner** [comment]
Hi Ryan, OK, I've just sent you a pull request, thanks again for your great help and contribution of this gem!! Thank you so much :)

**Comment by shanys8** [comment]
So I booked and confirmed a purchase and now I'm trying to cancel it that way:
    @cancel_operation = @client.cancel_purchase({PurchaseReference: {
        FileNumber: @checkout_response.purchase.reference.file_number,
        IncomingOffice: { code: @checkout_response.purchase.reference.incoming_office_code }
        }
    })
when file_number and incoming_office_code not empty, and getting this error:
'Purchase reference can't be blank'
What am I missing? can you please provide an example?

**Comment by shanys8** [comment]
Edward,
If you could add to the pull request a spec for the cancel purchase method
that would be great! :)
Thank you guys!

**Comment by netloner** [comment]
Hi shany:
 
   You may try to use the lowercase keys, just like the naming conventions in Rails, for example:
```ruby     
    @view_cancel_operation = @client.cancel_purchase({
                                                         purchase_reference: {
                                                             file_number: @hb_order.file_number,
                                                             incoming_office: @hb_order.incoming_office
                                                         },
                                                         view_or_cancel: "C"
                                                     })

    if @view_cancel_operation.errors.any?
      redirect_to :back, :alert => "[HOTELBED ERROR] #{@view_cancel_operation.errors.full_messages.join("\n")}"     
    end     
```

  OK, I'll put it in a spec test example file later :+1:

**Comment by shanys8** [comment]
Bam! it worked, thanks :)

**Comment by shanys8** [comment]
When will the pull request with the cancellation purchase be merged into the gem?

**Comment by ryantownsend** [comment]
Apologies for the delay, this has now been merged.
